### ISSUE TITLE
Wrong dimension for pi softmax

### ISSUE THREAD

**Issue by RobinKa** [ctallec/world-models#10]
Hey,

https://github.com/ctallec/world-models/blob/master/models/mdrnn.py#L100

```python
pi = pi.view(seq_len, bs, self.gaussians)
logpi = f.log_softmax(pi, dim=-2)
```

Here the softmax is done over the batch dimension of pi. Shouldn't the softmax be done over the gaussians dimension (ie. `dim=-1` instead of `dim=-2`)?

**Comment by ctallec** [comment]
You are right ! I'm fixing this and checking that nothing breaks asap !
