### ISSUE TITLE
I try to train vae in pytorch 1.0,  Failed

### ISSUE THREAD

**Issue by snowzjy** [ctallec/world-models#11]
I find BCE and KLD are all nan. Could the code update for pytorch 1.0? I will very thankfull !

**Comment by zuoanqh** [comment]
I had this error on GPU only but not CPU. If that's your case, it's probably due to underflow from using float tensors on the GPU. I changed torch's default tensor to double, and had the dataset loader load into double ndarraies, and it was fixed.

**Comment by leonardblier** [comment]
I have the same problem ... It seems to be a problem of conv2dtranspose with CUDNN. I wrote a minimal code reproducing this bug and  opened an issue on the pytorch repo : https://github.com/pytorch/pytorch/issues/16610

**Comment by ctallec** [comment]
The latest push should fix this. 
torch.backends.cudnn.benchmark is set to True, this slows down performances a bit, but you should not get NaNs while training under pytorch 1.0.
