### ISSUE TITLE
Reparameterization trick coefficient

### ISSUE THREAD

**Issue by skinnersBoxy** [ctallec/world-models#13]
I'm reimplementing world-models as an exercise in learning pytorch and I noticed that the reparameterization trick in the VAE is implemented slightly differently here and in the [original tensorflow](https://github.com/hardmaru/WorldModelsExperiments/blob/master/carracing/vae/vae.py). Specifically, in the original, they reparameterize with [z = epsilon*exp(log_sigma / 2) + mu](https://github.com/pytorch/examples/blob/master/vae/main.py#L53), and in this code we just do [z = epsilon*exp(log_sigma) + mu](https://github.com/ctallec/world-models/blob/master/models/vae.py#L72). I'm not very familiar with VAEs, and so I wanted to make sure that this all worked out to the same results, maybe because the encoder weights will double or something. Does this always hash out the same? If we regularize the encoder weights, does it still turn out the same? Is one or the other more correct?

**Comment by ctallec** [comment]
If log_sigma is the log of you standard deviation, then the reparameterization trick should be written as z = epsilon*exp(log_sigma) + mu (it's just mu + std * epsilon) but that's just a matter of how you parameterize your standard deviation. In practice, I don't think this would make a huge difference.
