### ISSUE TITLE
[Error] Can not train VAE

### ISSUE THREAD

**Issue by Ivorra** [ctallec/world-models#14]
Hi, I am trying to train the VAE (with the step 2 command), but when it tries to load the dataset (dataset/carracing) it gives the following error:

Traceback (most recent call last):
  File "trainvae.py", line 63, in <module>
    dataset_train, batch_size=args.batch_size, shuffle=True, num_workers=2)
  File "/home/s1881460/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "/home/s1881460/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 60, in __init__
    self.num_samples = len(self.data_source)
  File "/mnt/mscteach_home/s1881460/world-models/data/loaders.py", line 55, in __len__
    self.load_next_buffer()
  File "/mnt/mscteach_home/s1881460/world-models/data/loaders.py", line 34, in load_next_buffer
    self._buffer_index = self._buffer_index % len(self._files)
ZeroDivisionError: integer division or modulo by zero

Thanks!

**Comment by ctallec** [comment]
Have you generated the dataset using the first command ? If not, first generate the dataset, then launch the second command. Otherwise, can you check that your datasets/carracing folder is not empty (beware, there's an s at the end of dataset, if you generated in dataset/carracing, this might be the cause of your issue) ?

**Comment by Ivorra** [comment]
I generated the dataset with the same command structure, but used 500 rollouts and 64 threads. And yes, I meant datasets with "s". So the path to my *.npz is "world-models/datasets/carracing/thread_x/rollout_y.npz", where _x_ goes from 0 to 63, and _y_ goes from 0 to 1.

Should I run the first command with 1000 rollouts?

Thanks!

**Comment by ctallec** [comment]
Ok, this is probably the problem, you need to generate at least 601 rollouts ... That's a bit hardcoded, but basically we are using the first 600 rollout files to train and the rest to test. If you generate at least 800 rollouts (to have a decent test set) you should be fine.

**Comment by Ivorra** [comment]
Alright, I will try to get >601 and report back!

**Comment by ctallec** [comment]
Small correction, we use the 600 lasts as test set, and the rest as train set.

**Comment by Ivorra** [comment]
The VAE is finally training, thanks!
