### ISSUE TITLE
trainmdrnn running only test, the test loss decreases?

### ISSUE THREAD

**Issue by ranahanocka** [ctallec/world-models#16]
I noticed a behavior which is a bit odd. If I comment out the line which runs training in trainmdrnn.py [see here](https://github.com/ctallec/world-models/blob/dbc0de15efa013f712ca583eba5e2989e74a1618/trainmdrnn.py#L202) which means I am only running test, the test error loss is decreasing.
I am confused as to how this can be, since no gradients should be updating anything during test, right?

ETA:
I added this snippet of code in the data_pass
```
        wsum = 0
        for w in list(mdrnn.parameters()):
            wsum += torch.norm(w)
        print(wsum.item())
```

and it looks like the mdrnn weights indeed aren't changing during test (only during train) -- but I am still not sure how the test loss can be decreasing.

**Comment by ctallec** [comment]
I cannot reproduce your issue. If I comment the training part in the MDRNN file, what I get is a test loss that fluctuates around 1.39 (fluctuations come from the randomization of the test subset).
