### ISSUE TITLE
Shouldn't this be outside the for loop?

### ISSUE THREAD

**Issue by Ivorra** [ctallec/world-models#19]
The variable _is_best_ is set to _None_ each time inside the for loop, shouldn't it be outside the loop, as in _trainvae.py_?

https://github.com/ctallec/world-models/blob/dbc0de15efa013f712ca583eba5e2989e74a1618/trainmdrnn.py#L201

**Comment by AmazingAng** [comment]
I think u are right. This replace the best model with current model every time.

**Comment by Ivorra** [comment]
Thanks!

**Comment by leonardblier** [comment]
@Ivorra 
You are totally right, this is a mistake. Could you make a Pull Request on this please? Thanks!
