### ISSUE TITLE
Different transform in trainvae.py & trainmdrnn.py

### ISSUE THREAD

**Issue by AmazingAng** [ctallec/world-models#21]
In trainvae.py:
transform_test = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((RED_SIZE, RED_SIZE)),
    transforms.ToTensor(),
])

While in trainmdrnn.py:
 transform = transforms.Lambda(
    lambda x: np.transpose(x, (0, 3, 1, 2)) / 255)

I don't quite understand why there would be such difference and its consequences for the encoder processing of VAE model.

**Comment by leonardblier** [comment]
Indeed, I don't think there is any reason for this difference. 
Still, the two different preprocessing pipelines should be equivalent. The only operation missing in the code you quoted is, in trainmdrnn, the `Resize` operation. This operation is done later in `to_latent`.

**Comment by AmazingAng** [comment]
I see.
Thanks!
