### ISSUE TITLE
sleep(0.1) leads to infty loops

### ISSUE THREAD

**Issue by JiahaoYao** [ctallec/world-models#23]
Hi, I find `sleep(0.1)` leads to infty loops in your `traincontroller.py`: https://github.com/ctallec/world-models/blob/master/traincontroller.py#L95-L97 and https://github.com/ctallec/world-models/blob/master/traincontroller.py#L137-L138.

Could you help?

**Comment by JiahaoYao** [comment]
Issue solved.

**Comment by megsano** [comment]
How did you solve this?

**Comment by mkj3085003** [comment]
Please, I seem to have the same problem, can you tell me how it was solved?
