### ISSUE TITLE
inconsisent MDRNN / MDRNNCell behavoir

### ISSUE THREAD

**Issue by ranahanocka** [ctallec/world-models#24]
there is different behavoir when running MDRNN vs. MDRNNCell. Specifically, I give MDRNN and MDRNNCell the same input (MDRNN is batched_sequences in the input, then I take only one sequence from the output, and compare that against the same sequence as input to the MDRNNCell). I observe that the mus and sigmas match up, but the logpi does not. The issue is related to the dimension of the softmax. 

Specifically, in MDRNN the softmax is applied along the last dimension: (e.g., for a 32x16x5 input, along dimension with 5)

https://github.com/ctallec/world-models/blob/b711934f20651cbe4f6e6cc357cacdac00866d26/models/mdrnn.py#L100

Where as is MDRNNCell the softmax is applied along the first input (e.g., for a 16x5 input, softmax is applied along dimension with 16).

https://github.com/ctallec/world-models/blob/b711934f20651cbe4f6e6cc357cacdac00866d26/models/mdrnn.py#L148

I notice that this was changed in this commit:
https://github.com/ctallec/world-models/commit/5d4261e5406fb4724e3617ab4d94bde909374a26#diff-949b6b6e9db2dd11dbf333ec6fff33ed

**Comment by ctallec** [comment]
You are right, I'm fixing this asap. If I'm not mistaken, this should not affect performance (the MDRNNCell is only used when training the controller, and in this case, we only rely on the hidden state of the RNN, not its outputs).

**Comment by ranahanocka** [comment]
Cool, thanks for confirming!

Right. So in the original paper / implementation there was a variant where the MDRNN was used to predict the next state, in the "virtual" or "dream world" to train the controller. (So in that scenario it matters.)

BTW -- do you have any  plans to implement the virtual environment in this repo? That would be really useful!

**Comment by ctallec** [comment]
Yep indeed, this would impact training in the simulated environment, which is currently not implemented.
Both Léonard and I are quite busy at the moment, so we are not planning on implementing training in the dreamt environment in the near future. There is an untested facility to simulate rollouts using the trained VAE and MDN-RNN in envs/simulated_carracing.py. If you are willing to adapt this to allow for training in the dream, I would gladly review the PR !
