### ISSUE TITLE
untrained RNN

### ISSUE THREAD

**Issue by wensdong** [ctallec/world-models#7]
Interesting to learn that an untrained RNN will produce the same result as trained, I was having the same doubt about the value of predicting the "Z(t+1)".
 Question is: If RNN untrained, then "h" suppose to be random, how this "h" will contribute to the training of the controller?

**Comment by teytaud** [comment]
Maybe the reservoir computing paradigm answers your question:
https://en.wikipedia.org/wiki/Echo_state_network

and https://ctallec.github.io/world-models/ also contains an explanation:
<<Our interpretation of this phenomenon is that even if the recurrent model is not able to predict the next state of the environment, its recurrent state still contains some crucial information on the environment dynamic. >>    (h is not random, just the weights generating it are random...)

**Comment by ctallec** [comment]
As @teytaud mentionned, we believe the reservoir computing effect might explain this result. Basically, even when the weights or the RNN are random, the recurrent state of the RNN still carries information about past events.

**Comment by wensdong** [comment]
"(h is not random, just the weights generating it are random...)".  
h=Whh*h+Whz*Z+Wha*A+ bias and the Weight matrices is random **but fixed,** at every time step, h is generated with **the same** **fixed Weight matrices.** Therefore h contain historical information about Z and A at each time step. 
For Car Racing game, I think there is no point to train RNN to predict next  frame as current frame give you enough information about what the agent should do next. One extra frame won't give you much more advantage.
I believe you can try to train an controller without Z but only h. you can still get pretty good result.

**Comment by ctallec** [comment]
"For Car Racing game, I think there is no point to train RNN to predict next frame as current frame give you enough information about what the agent should do next. One extra frame won't give you much more advantage." With only one frame you don't have access to the notion of speed of the car, which is probably useful to get very good performances. The original paper experimented with this setup (where you only feed z to the controller) and found that results were significantly tamed down.

**Comment by wensdong** [comment]
Agree with you, I was referring human driving experience on that.  you can ignore the quoted line.

**Comment by wensdong** [comment]
Well explained!
