### ISSUE TITLE
Controller training random stop

### ISSUE THREAD

**Issue by wensdong** [ctallec/world-models#9]
Please find the following errors:

[errorController.txt](https://github.com/ctallec/world-models/files/2238220/errorController.txt)
[errorController1.txt](https://github.com/ctallec/world-models/files/2238221/errorController1.txt)

 The training result also looks bad:
Loading VAE at epoch 33 with test loss 34.16893509338379
Loading MDRNN at epoch 29 with test loss 1.053613607351445
Loading Controller with reward 316.7092720531355

**Comment by ctallec** [comment]
The VAE and MDRNN achieve decent results. The two errors you obtain are CMAES related. I guess this could be related to a n-samples set too low. In our replication, we used n-samples=16 and pop-size=4. If you could try with these values and keep me updated. I will investigate too.

**Comment by wensdong** [comment]
Thanks so much! Now there is no error for controller training. However, it seems going nowhere, I loaded some info below:
----------------------------------------------------------------------------------
Loading VAE at epoch 33 with test loss 34.16893509338379
Loading MDRNN at epoch 29 with test loss 1.053613607351445
Loading Controller with reward 352.99061245415896
----------------------------------------------------------------------
![trainingscreenshot2](https://user-images.githubusercontent.com/18463724/43502571-72942542-9553-11e8-805d-41b01b1a4d0d.png)
![trainingscreenshot1](https://user-images.githubusercontent.com/18463724/43502575-749f7f76-9553-11e8-99c0-0950caaedabb.png)
[trainControllerGoingNowhereAfter200gen2.txt](https://github.com/ctallec/world-models/files/2248095/trainControllerGoingNowhereAfter200gen2.txt)

**Comment by wensdong** [comment]
Thanks so much! this fix worked! However, the training is going nowhere after 200 generations:
"python traincontroller.py --logdir exp_dir --n-samples 16
 --pop-size 4 --target-return 950 --display --max-workers 12"

Loading VAE at epoch 33 with test loss 34.16893509338379
Loading MDRNN at epoch 29 with test loss 1.053613607351445
Loading Controller with reward 352.99061245415896
[trainControllerGoingNowhereAfter200gen2.txt](https://github.com/ctallec/world-models/files/2248116/trainControllerGoingNowhereAfter200gen2.txt)
![trainingscreenshot1](https://user-images.githubusercontent.com/18463724/43502811-83555dfa-9554-11e8-8534-cf88748fd162.png)

**Comment by wensdong** [comment]
Changed pop-size ==16 and
Current evaluation: -619.9075467084033 after 100 gens

**Comment by wensdong** [comment]
it seems working
